#ifndef NEON_OUBLIETTE_ECS_SYSTEMS_CITY_GENERATION_SYSTEM_H
#define NEON_OUBLIETTE_ECS_SYSTEMS_CITY_GENERATION_SYSTEM_H

#include <entt/entt.hpp>
#include "../components/components.h"
#include "../components/zoning_components.h"
#include "../components/simulation_layers.h"
#include "../system_scheduler.h"
#include <string>
#include <set>
#include <random>

namespace NeonOubliette {

/**
 * @brief Handles the actual placement of tiles and building entities
 *        based on the logical MacroZones generated by ZoningSolverSystem.
 */
class CityGenerationSystem : public ISystem {
public:
    CityGenerationSystem(entt::registry& registry, entt::dispatcher& dispatcher)
        : m_registry(registry), m_dispatcher(dispatcher) {}

    void initialize() override {}
    void update(double delta_time) override {}

    /**
     * @brief Generates the city by iterating through MacroZone entities.
     */
    void generateCityFromZones() {
        auto config_view = m_registry.view<WorldConfigComponent>();
        if (config_view.empty()) return;
        auto& config = config_view.get<WorldConfigComponent>(config_view.front());

        auto zone_view = m_registry.view<MacroZoneComponent>();
        
        for (auto entity : zone_view) {
            const auto& zone = zone_view.get<MacroZoneComponent>(entity);
            generateZoneInterior(zone, config.macro_cell_size);
        }
    }

private:
    void generateZoneInterior(const MacroZoneComponent& zone, int cell_size) {
        int start_x = zone.macro_x * cell_size;
        int start_y = zone.macro_y * cell_size;

        std::random_device rd;
        std::mt19937 gen(rd());
        std::set<std::pair<int, int>> building_footprint;

        // Place zone-appropriate buildings
        std::uniform_real_distribution<> dis(0.0, 1.0);
        if (dis(gen) < zone.density) {
            int bw = 4 + (int)(dis(gen) * 6);
            int bh = 4 + (int)(dis(gen) * 6);
            int bx = start_x + (cell_size - bw) / 2;
            int by = start_y + (cell_size - bh) / 2;
            
            std::string building_name = "Structure";
            std::string building_color = "#FFFFFF";
            int floors = 1;

            switch(zone.type) {
                case ZoneType::CORPORATE:
                    building_name = "Corporate Block"; building_color = "#0055FF"; floors = 10;
                    break;
                case ZoneType::SLUM:
                    building_name = "Shanty"; building_color = "#884400"; floors = 1;
                    break;
                case ZoneType::INDUSTRIAL:
                    building_name = "Factory"; building_color = "#AA2200"; floors = 2;
                    break;
                case ZoneType::RESIDENTIAL:
                    building_name = "Hab-Unit"; building_color = "#00AA44"; floors = 4;
                    break;
                default: break;
            }

            if (zone.type != ZoneType::TRANSIT && zone.type != ZoneType::PARK && zone.type != ZoneType::VOID) {
                createBuildingShell(building_name, bx, by, bw, bh, floors, building_color, zone.type);
                for (int fx = bx; fx < bx + bw; ++fx) {
                    for (int fy = by; fy < by + bh; ++fy) {
                        building_footprint.insert({fx, fy});
                    }
                }
            }
        }

        // Fill remaining tiles with base terrain
        for (int x = start_x; x < start_x + cell_size; ++x) {
            for (int y = start_y; y < start_y + cell_size; ++y) {
                if (building_footprint.count({x, y})) continue;

                // Default terrain for zone
                TerrainType type = TerrainType::GRASS;
                char glyph = '"';
                std::string color = "#004400";

                switch(zone.type) {
                    case ZoneType::CORPORATE:
                        type = TerrainType::SIDEWALK; glyph = '.'; color = "#111111";
                        break;
                    case ZoneType::SLUM:
                        type = TerrainType::DIRT; glyph = '\''; color = "#443322";
                        break;
                    case ZoneType::INDUSTRIAL:
                        type = TerrainType::CONCRETE_FLOOR; glyph = '.'; color = "#222222";
                        break;
                    case ZoneType::RESIDENTIAL:
                        type = TerrainType::GRASS; glyph = '"'; color = "#004400";
                        break;
                    case ZoneType::TRANSIT:
                        type = TerrainType::STREET; glyph = ' '; color = "#333333";
                        break;
                    default: break;
                }

                createTile(x, y, 0, type, glyph, color);
            }
        }
    }

    void createTile(int x, int y, int layer, TerrainType type, char glyph, std::string color) {
        auto e = m_registry.create();
        m_registry.emplace<PositionComponent>(e, x, y, layer);
        m_registry.emplace<TerrainComponent>(e, type);
        m_registry.emplace<RenderableComponent>(e, glyph, color, layer);
        m_registry.emplace<Layer0PhysicsComponent>(e);
        if (type == TerrainType::WALL) m_registry.emplace<ObstacleComponent>(e);
    }

    void createBuildingShell(std::string name, int x, int y, int w, int h, int floors, std::string color, ZoneType ztype) {
        auto building = m_registry.create();
        m_registry.emplace<NameComponent>(building, name);
        m_registry.emplace<PositionComponent>(building, x, y, 0);
        m_registry.emplace<BuildingComponent>(building, floors, ztype, 0);
        m_registry.emplace<SizeComponent>(building, w, h);
        m_registry.emplace<Layer0PhysicsComponent>(building);
        m_registry.emplace<PropertyComponent>(building); // Economic layer hook

        for (int cur_x = x; cur_x < x + w; ++cur_x) {
            for (int cur_y = y; cur_y < y + h; ++cur_y) {
                bool is_edge = (cur_x == x || cur_x == x + w - 1 || cur_y == y || cur_y == y + h - 1);
                if (is_edge) {
                    if (cur_y == y + h - 1 && cur_x == x + (w/2)) {
                        auto door = m_registry.create();
                        m_registry.emplace<PositionComponent>(door, cur_x, cur_y, 0);
                        m_registry.emplace<RenderableComponent>(door, '+', "#FFFF00", 0);
                        m_registry.emplace<NameComponent>(door, name + " Entrance");
                        m_registry.emplace<BuildingEntranceComponent>(door, building, 0);
                        // Also create a floor tile under the door so it's walkable
                        createTile(cur_x, cur_y, 0, TerrainType::CONCRETE_FLOOR, '.', "#111111");
                    } else {
                        createTile(cur_x, cur_y, 0, TerrainType::WALL, '#', color);
                    }
                } else {
                    createTile(cur_x, cur_y, 0, TerrainType::CONCRETE_FLOOR, '.', "#111111");
                }
            }
        }
    }

    entt::registry& m_registry;
    entt::dispatcher& m_dispatcher;
};

} // namespace NeonOubliette

#endif // NEON_OUBLIETTE_ECS_SYSTEMS_CITY_GENERATION_SYSTEM_H
