#include "serialization_system.h"

#include <cereal/archives/binary.hpp>
#include <entt/entity/snapshot.hpp>
#include <fstream>

#include "../components/components.h"
#include "../components/simulation_layers.h"
#include "../components/zoning_components.h"
#include "../components/infrastructure_components.h"
#include "../components/transit_components.h"

namespace NeonOubliette {

SerializationSystem::SerializationSystem(entt::registry& registry, entt::dispatcher& dispatcher)
    : registry(registry), dispatcher(dispatcher) {
}

void SerializationSystem::save_game(const std::string& filename) {
    std::ofstream os(filename, std::ios::binary);
    if (!os.is_open()) return;

    cereal::BinaryOutputArchive archive(os);

    entt::snapshot{registry}
        .get<entt::entity>(archive)
        .get<NeonOubliette::NameComponent>(archive)
        .get<NeonOubliette::PositionComponent>(archive)
        .get<NeonOubliette::RenderableComponent>(archive)
        .get<NeonOubliette::PlayerComponent>(archive)
        .get<NeonOubliette::ObstacleComponent>(archive)
        .get<NeonOubliette::PlayerCurrentLayerComponent>(archive)
        .get<NeonOubliette::InventoryComponent>(archive)
        .get<NeonOubliette::ItemComponent>(archive)
        .get<NeonOubliette::AgentComponent>(archive)
        .get<NeonOubliette::NeedsComponent>(archive)
        .get<NeonOubliette::ConsumableComponent>(archive)
        .get<NeonOubliette::CityComponent>(archive)
        .get<NeonOubliette::RoadComponent>(archive)
        .get<NeonOubliette::RailNetworkComponent>(archive)
        .get<NeonOubliette::BuildingComponent>(archive)
        .get<NeonOubliette::ResourceNodeComponent>(archive)
        .get<NeonOubliette::CitizenComponent>(archive)
        .get<NeonOubliette::HousingPreferenceComponent>(archive)
        .get<NeonOubliette::GlobalResourceStockpile>(archive)
        .get<NeonOubliette::BudgetComponent>(archive)
        .get<NeonOubliette::TaxationComponent>(archive)
        .get<NeonOubliette::MacroMarketComponent>(archive)
        .get<NeonOubliette::WorkstationComponent>(archive)
        .get<NeonOubliette::FloorComponent>(archive)
        .get<NeonOubliette::RoomComponent>(archive)
        .get<NeonOubliette::ApartmentComponent>(archive)
        .get<NeonOubliette::NPCComponent>(archive)
        .get<NeonOubliette::ContainedByComponent>(archive)
        .get<NeonOubliette::ShopComponent>(archive)
        .get<NeonOubliette::ResidentComponent>(archive)
        .get<NeonOubliette::UtilityAllocationComponent>(archive)
        .get<NeonOubliette::VehicleComponent>(archive)
        .get<NeonOubliette::ElevatorControlComponent>(archive)
        .get<NeonOubliette::InteractionQueue>(archive)
        .get<NeonOubliette::RelationshipComponent>(archive)
        .get<NeonOubliette::FactionComponent>(archive)
        .get<NeonOubliette::PublicOpinionComponent>(archive)
        .get<NeonOubliette::InfluenceComponent>(archive)
        .get<NeonOubliette::BeliefComponent>(archive)
        .get<NeonOubliette::VoterComponent>(archive)
        .get<NeonOubliette::FactionAffiliationComponent>(archive)
        .get<NeonOubliette::CandidateComponent>(archive)
        .get<NeonOubliette::PromiseComponent>(archive)
        .get<NeonOubliette::LieComponent>(archive)
        .get<NeonOubliette::ElectedOfficeComponent>(archive)
        .get<NeonOubliette::BillComponent>(archive)
        .get<NeonOubliette::BriberyComponent>(archive)
        .get<NeonOubliette::FavorComponent>(archive)
        .get<NeonOubliette::BlackMarketComponent>(archive)
        .get<NeonOubliette::BackroomDealComponent>(archive)
        .get<NeonOubliette::CreatureComponent>(archive)
        .get<NeonOubliette::ForageNodeComponent>(archive)
        .get<NeonOubliette::WasteComponent>(archive)
        .get<NeonOubliette::PollutionLevelComponent>(archive)
        .get<NeonOubliette::PipeSegmentComponent>(archive)
        .get<NeonOubliette::WaterQualityComponent>(archive)
        .get<NeonOubliette::WorkOrderComponent>(archive)
        .get<NeonOubliette::RepairProgressComponent>(archive)
        .get<NeonOubliette::SkillComponent>(archive)
        .get<NeonOubliette::JobRequirementComponent>(archive)
        .get<NeonOubliette::EmploymentContractComponent>(archive)
        .get<NeonOubliette::StairsComponent>(archive)
        .get<NeonOubliette::ElevatorComponent>(archive)
        .get<NeonOubliette::ShaftComponent>(archive)
        .get<NeonOubliette::VerticalFloorComponent>(archive)
        .get<NeonOubliette::CeilingComponent>(archive)
        .get<NeonOubliette::VerticalViewComponent>(archive)
        .get<NeonOubliette::HUDComponent>(archive)
        .get<NeonOubliette::GoalComponent>(archive)
        .get<NeonOubliette::AgentTaskComponent>(archive)
        .get<NeonOubliette::ContainerComponent>(archive)
        .get<NeonOubliette::CurrentPathComponent>(archive)
        .get<NeonOubliette::BuildingEntranceComponent>(archive)
        .get<NeonOubliette::InteriorGeneratedComponent>(archive)
        .get<NeonOubliette::Layer0PhysicsComponent>(archive)
        .get<NeonOubliette::Layer1BiologyComponent>(archive)
        .get<NeonOubliette::Layer2CognitiveComponent>(archive)
        .get<NeonOubliette::Layer3EconomicComponent>(archive)
        .get<NeonOubliette::Layer4PoliticalComponent>(archive)
        .get<NeonOubliette::MacroZoneComponent>(archive)
        .get<NeonOubliette::PropertyComponent>(archive)
        .get<NeonOubliette::HeatIslandComponent>(archive)
        .get<NeonOubliette::WeatherComponent>(archive)
        .get<NeonOubliette::PatrolComponent>(archive)
        .get<NeonOubliette::InfrastructureArterialComponent>(archive)
        .get<NeonOubliette::ConduitFieldComponent>(archive)
        .get<NeonOubliette::InfrastructureNodeComponent>(archive)
        .get<NeonOubliette::PersonalVehicleComponent>(archive)
        .get<NeonOubliette::TransitOccupantsComponent>(archive)
        .get<NeonOubliette::RidingComponent>(archive)
        .get<NeonOubliette::TransitVehicleComponent>(archive)
        .get<NeonOubliette::TransitRouteComponent>(archive)
        .get<NeonOubliette::TransitStationComponent>(archive);
}

void SerializationSystem::load_game(const std::string& filename) {
    std::ifstream is(filename, std::ios::binary);
    if (!is.is_open()) return;

    cereal::BinaryInputArchive archive(is);
    registry.clear();

    entt::snapshot_loader{registry}
        .get<entt::entity>(archive)
        .get<NeonOubliette::NameComponent>(archive)
        .get<NeonOubliette::PositionComponent>(archive)
        .get<NeonOubliette::RenderableComponent>(archive)
        .get<NeonOubliette::PlayerComponent>(archive)
        .get<NeonOubliette::ObstacleComponent>(archive)
        .get<NeonOubliette::PlayerCurrentLayerComponent>(archive)
        .get<NeonOubliette::InventoryComponent>(archive)
        .get<NeonOubliette::ItemComponent>(archive)
        .get<NeonOubliette::AgentComponent>(archive)
        .get<NeonOubliette::NeedsComponent>(archive)
        .get<NeonOubliette::ConsumableComponent>(archive)
        .get<NeonOubliette::CityComponent>(archive)
        .get<NeonOubliette::RoadComponent>(archive)
        .get<NeonOubliette::RailNetworkComponent>(archive)
        .get<NeonOubliette::BuildingComponent>(archive)
        .get<NeonOubliette::ResourceNodeComponent>(archive)
        .get<NeonOubliette::CitizenComponent>(archive)
        .get<NeonOubliette::HousingPreferenceComponent>(archive)
        .get<NeonOubliette::GlobalResourceStockpile>(archive)
        .get<NeonOubliette::BudgetComponent>(archive)
        .get<NeonOubliette::TaxationComponent>(archive)
        .get<NeonOubliette::MacroMarketComponent>(archive)
        .get<NeonOubliette::WorkstationComponent>(archive)
        .get<NeonOubliette::FloorComponent>(archive)
        .get<NeonOubliette::RoomComponent>(archive)
        .get<NeonOubliette::ApartmentComponent>(archive)
        .get<NeonOubliette::NPCComponent>(archive)
        .get<NeonOubliette::ContainedByComponent>(archive)
        .get<NeonOubliette::ShopComponent>(archive)
        .get<NeonOubliette::ResidentComponent>(archive)
        .get<NeonOubliette::UtilityAllocationComponent>(archive)
        .get<NeonOubliette::VehicleComponent>(archive)
        .get<NeonOubliette::ElevatorControlComponent>(archive)
        .get<NeonOubliette::InteractionQueue>(archive)
        .get<NeonOubliette::RelationshipComponent>(archive)
        .get<NeonOubliette::FactionComponent>(archive)
        .get<NeonOubliette::PublicOpinionComponent>(archive)
        .get<NeonOubliette::InfluenceComponent>(archive)
        .get<NeonOubliette::BeliefComponent>(archive)
        .get<NeonOubliette::VoterComponent>(archive)
        .get<NeonOubliette::FactionAffiliationComponent>(archive)
        .get<NeonOubliette::CandidateComponent>(archive)
        .get<NeonOubliette::PromiseComponent>(archive)
        .get<NeonOubliette::LieComponent>(archive)
        .get<NeonOubliette::ElectedOfficeComponent>(archive)
        .get<NeonOubliette::BillComponent>(archive)
        .get<NeonOubliette::BriberyComponent>(archive)
        .get<NeonOubliette::FavorComponent>(archive)
        .get<NeonOubliette::BlackMarketComponent>(archive)
        .get<NeonOubliette::BackroomDealComponent>(archive)
        .get<NeonOubliette::CreatureComponent>(archive)
        .get<NeonOubliette::ForageNodeComponent>(archive)
        .get<NeonOubliette::WasteComponent>(archive)
        .get<NeonOubliette::PollutionLevelComponent>(archive)
        .get<NeonOubliette::PipeSegmentComponent>(archive)
        .get<NeonOubliette::WaterQualityComponent>(archive)
        .get<NeonOubliette::WorkOrderComponent>(archive)
        .get<NeonOubliette::RepairProgressComponent>(archive)
        .get<NeonOubliette::SkillComponent>(archive)
        .get<NeonOubliette::JobRequirementComponent>(archive)
        .get<NeonOubliette::EmploymentContractComponent>(archive)
        .get<NeonOubliette::StairsComponent>(archive)
        .get<NeonOubliette::ElevatorComponent>(archive)
        .get<NeonOubliette::ShaftComponent>(archive)
        .get<NeonOubliette::VerticalFloorComponent>(archive)
        .get<NeonOubliette::CeilingComponent>(archive)
        .get<NeonOubliette::VerticalViewComponent>(archive)
        .get<NeonOubliette::HUDComponent>(archive)
        .get<NeonOubliette::GoalComponent>(archive)
        .get<NeonOubliette::AgentTaskComponent>(archive)
        .get<NeonOubliette::ContainerComponent>(archive)
        .get<NeonOubliette::CurrentPathComponent>(archive)
        .get<NeonOubliette::BuildingEntranceComponent>(archive)
        .get<NeonOubliette::InteriorGeneratedComponent>(archive)
        .get<NeonOubliette::Layer0PhysicsComponent>(archive)
        .get<NeonOubliette::Layer1BiologyComponent>(archive)
        .get<NeonOubliette::Layer2CognitiveComponent>(archive)
        .get<NeonOubliette::Layer3EconomicComponent>(archive)
        .get<NeonOubliette::Layer4PoliticalComponent>(archive)
        .get<NeonOubliette::MacroZoneComponent>(archive)
        .get<NeonOubliette::PropertyComponent>(archive)
        .get<NeonOubliette::HeatIslandComponent>(archive)
        .get<NeonOubliette::WeatherComponent>(archive)
        .get<NeonOubliette::PatrolComponent>(archive)
        .get<NeonOubliette::InfrastructureArterialComponent>(archive)
        .get<NeonOubliette::ConduitFieldComponent>(archive)
        .get<NeonOubliette::InfrastructureNodeComponent>(archive)
        .get<NeonOubliette::PersonalVehicleComponent>(archive)
        .get<NeonOubliette::TransitOccupantsComponent>(archive)
        .get<NeonOubliette::RidingComponent>(archive)
        .get<NeonOubliette::TransitVehicleComponent>(archive)
        .get<NeonOubliette::TransitRouteComponent>(archive)
        .get<NeonOubliette::TransitStationComponent>(archive)
        .orphans();
}

} // namespace NeonOubliette
